# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [20]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [22]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns = data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [24]:
from sklearn.linear_model import LinearRegression

boston_linear_model = LinearRegression()
boston_linear_model.fit(X_train, y_train)
#print(boston_linear_model.coef_)
#Con esto hacemos el Predict
y_pred_text = boston_linear_model.predict(X_test)
#print(y_pred_text)
y_pred_train = boston_linear_model.predict(X_train)
#print(y_pred_train)



## 3. Calculate and print R-squared for both the training and the testing set.

In [25]:
print('R`2 = {}'.format(boston_linear_model.score(X_train, y_train)))
print('R`2 = {}'.format(boston_linear_model.score(X_test, y_test)))

R`2 = 0.7397393375001053
R`2 = 0.7348142948097967


## 4. Calculate and print mean squared error for both the training and the testing set.

In [26]:
from sklearn.metrics import mean_squared_error

y = mean_squared_error(y_test, y_pred_text)
z = mean_squared_error(y_train, y_pred_train)
print(y)
print(z)

24.386414491900496
21.422498088222405


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [27]:
from sklearn.metrics import mean_absolute_error

y = mean_absolute_error(y_test, y_pred_text)
z = mean_absolute_error(y_train, y_pred_train)
print(y)
print(z)

3.3331501347830463
3.1919663713680957


## Classification Model Evaluation

In [28]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [30]:
from sklearn.linear_model import LogisticRegression

data2 = LogisticRegression(solver="lbfgs")

data2.fit(X_train, y_train)
#print(model.coef_)
y_pred_test = data2.predict(X_test)
y_pred_train = data2.predict(X_train)


/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [31]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred_test))
print(accuracy_score(y_train, y_pred_train))

0.9666666666666667
0.9583333333333334


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [32]:
from sklearn.metrics import balanced_accuracy_score
print((balanced_accuracy_score(y_test, y_pred_test)))
print((balanced_accuracy_score(y_train, y_pred_train)))

0.9696969696969697
0.957905982905983


## 10. Calculate and print the precision score for both the training and the testing set.

In [33]:
from sklearn.metrics import precision_score
print(precision_score(y_test, y_pred_test, average="macro"))
print(precision_score(y_train, y_pred_train, average="macro"))

0.9696969696969697
0.957905982905983


## 11. Calculate and print the recall score for both the training and the testing set.

In [34]:
from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred_test, average="macro"))
print(recall_score(y_train, y_pred_train, average="macro"))

0.9696969696969697
0.957905982905983


## 12. Calculate and print the F1 score for both the training and the testing set.

In [35]:
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred_test, average="macro"))
print(f1_score(y_train, y_pred_train, average="macro"))

0.9682539682539683
0.9578059071729959


## 13. Generate confusion matrices for both the training and the testing set.

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
print(confusion_matrix(y_test, y_pred_test))

[[ 9  0  0]
 [ 0 10  0]
 [ 0  1 10]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.